name: Check New Listings

on:
  schedule:
    - cron: '0 */24 * * *' 
  workflow_dispatch:  

jobs:
  check-listings:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      RECIPIENT_EMAIL: simon-thiesen@hotmail.com
      PREVIOUS_LISTINGS: ${{ secrets.PREVIOUS_LISTINGS || '' }}  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install beautifulsoup4 requests sendgrid

    - name: Run script
      run: TvangsauktionerListings.py
